spring:
  application:
    name: user-service
    datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
      driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

#  datasource:
#    url: jdbc:postgresql://localhost:5432/user_service
#    username: postgres
#    password: 123456
#    driver-class-name: org.postgresql.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true

jwt:
  secret: DGpNSf0cVmk8gaM53vr/Sn/8QGbxCv2/CIGdmBQpjo8=

server:
  port: 8081

# Debug Logging Configuration
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.sj.userservice: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.data.jpa: DEBUG
    root: INFO

