spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

jwt:
  secret: ${JWT_SECRET}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.sj.userservice: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
