spring:
  config:
    import: file:C:/Users/sumit/sumit/freelancing/Project 2/ecommerce-platform/.env.local.properties
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}

server:
  port: ${USER_SERVICE_PORT}

logging:
  level:
    com.sj.userservice: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
