spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD:}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

jwt:
  secret: ${JWT_SECRET}

aws:
  s3:
    endpoint: ${AWS_S3_ENDPOINT}
    bucket: ${AWS_S3_BUCKET}
  credentials:
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}
  cloudfront:
    domain: ${CLOUDFRONT_DOMAIN}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    com.sj.product_service: INFO
