spring:
  config:
    import: file:C:/Users/sumit/sumit/freelancing/Project 2/ecommerce-platform/.env.local.properties
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:${USER_SERVICE_PORT}
              predicates:
                - Path=/api/v1/auth/**, /api/v1/users/**
            - id: product-service
              uri: http://localhost:${PRODUCT_SERVICE_PORT}
              predicates:
                - Path=/api/v1/products/**, /api/v1/categories/**
jwt:
  secret: ${JWT_SECRET}

server:
  port: ${GATEWAY_PORT}

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
