spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://user-service:8081
              predicates:
                - Path=/api/v1/auth/**, /api/v1/users/**

jwt:
  secret: DGpNSf0cVmk8gaM53vr/Sn/8QGbxCv2/CIGdmBQpjo8=

server:
  port: 8080

# Debug Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.security: DEBUG
    com.sj.api_gateway: DEBUG
    reactor.netty.http.client: DEBUG
    reactor.netty.http.server: DEBUG
    root: INFO

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,gateway
  endpoint:
    gateway:
      enabled: true