spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${USER_SERVICE_URL}
          predicates:
            - Path=/api/v1/auth/**, /api/v1/users/**
        - id: product-service
          uri: ${PRODUCT_SERVICE_URL}
          predicates:
            - Path=/api/v1/products/**, /api/v1/categories/**
jwt:
  secret: ${JWT_SECRET}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    org.springframework.cloud.gateway: INFO
